[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  # Set REACT_APP_TMDB_API_KEY in Netlify UI instead of committing it here
  # REACT_APP_TMDB_API_KEY = "set_in_netlify_ui"